# Generated by Django 5.0.2 on 2024-02-20 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_rename_recipe_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receitas.category'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='receitas/covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
