# Generated by Django 5.0.2 on 2024-02-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_alter_receita_category_alter_receita_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='slug',
            field=models.SlugField(),
        ),
    ]
