# Generated by Django 5.0.2 on 2024-02-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_alter_receita_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
